Repository ms-np/Clock-and-Follow-Along-Dropdown, pull requests merged in 2020-08, with the labels that each got.

#5 Styling
  development-strategy.md
  index.html
  style.css
Labels: enhancement, project 26

#7 done
  clock.css
  development-strategy.md
  index.html
  scripts/handlers/clock.js
  scripts/handlers/starter.js
  scripts/listeners/clock.js
  scripts/listeners/starter.js
  style.css
Labels: clock

#12 Dropdown enter
  .vscode/settings.json
  development-strategy.md
  index.html
  scripts/handlers/enter-handler.js
  scripts/listeners/enter-listener.js
  style.css
Labels: project 26
